### ISSUE TITLE
在各项功能都正常运行的情况下生成的每句语音都会包含"one slash"

### ISSUE THREAD

**Issue by ZacharyXia** [NsLearning/LangHelper#4]
https://user-images.githubusercontent.com/70338974/231738220-91101ac0-178d-4409-8c60-5a141ca08b28.mp4

看起来像一个错误代码

**Comment by NsLearning** [comment]
群里也有人报过这个问题，下一版会一起解决。

**Comment by NsLearning** [comment]
> 看起来像一个错误代码

群里也有人报过这个问题，下一版会一起解决。
